# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - main
  - dev

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Main
    displayName: "Main branch"
    condition: eq(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - job: MainJob
        displayName: "Main branch job"
        steps:
          - task: UseDotNet@2
            inputs:
              version: "6.0.x"
              packageType: sdk
          - task: DotNetCoreCLI@2
            inputs:
              command: publish
              arguments: "--configuration Release --output publish_output"
              projects: "**/az-function.csproj"
              publishWebProjects: false
              modifyOutputPath: false
              zipAfterPublish: false
          - task: ArchiveFiles@2
            displayName: "Archive files"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/publish_output"
              includeRootFolder: false
              archiveFile: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(System.DefaultWorkingDirectory)/build$(Build.BuildId).zip"
              artifactName: "drop"
          - task: AzureFunctionApp@1 # Add this at the end of your file
            inputs:
              azureSubscription: "MyServiceConnection"
              appType: functionAppLinux # default is functionApp
              appName: "fnapp-y3ac2abjvi3wq"
              package: $(System.DefaultWorkingDirectory)/**/*.zip
              runtimeStack: "DOTNET|6.0"
  - stage: Development
    displayName: "Development branch"
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    jobs:
      - job: DevJob
        displayName: "Development branch job"
        steps:
          - task: DotNetCoreCLI@2
            inputs:
              command: "restore"
              projects: "**/az-function.csproj"

          - task: DotNetCoreCLI@2
            inputs:
              command: "build"
              projects: "**/az-function.csproj"
              arguments: "--configuration Release"

          - task: DotNetCoreCLI@2
            inputs:
              command: "test"
              projects: "**/az-function-tests.csproj"
              arguments: "--configuration Release"
